services:
    ofelia:
        image: mcuadros/ofelia:latest
        depends_on:
            - palserver
        restart: always
        command: daemon --docker
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro

    palserver:
        build: palserver
        restart: always
        ports:
            - 8211:8211/udp
        volumes:
            - ./backup:/home/steam/backup
        environment:
            - CHECKOUT=
            - TZ=Asia/Taipei
        labels:
            ofelia.enabled: "true"
            ofelia.job-exec.backup.schedule: "@every 15m"
            ofelia.job-exec.backup.command: su steam -c "bash -c 'cd /home/steam/Steam/steamapps/common/PalServer/Pal/Saved ; git add . ; git commit -m \"Auto Backup\" ; git push -u origin master'"
        deploy:
            resources:
                limits:
                    cpus: "3.0"
                    memory: 4G
