FROM cm2network/steamcmd:root

# use git to backup the server
# comment out the line below if you don't want to use git
RUN apt update && apt install -y git

USER steam

RUN ./steamcmd.sh +login anonymous +app_update 2394010 validate +quit

#expose default ports
EXPOSE 8211/udp

#update server at the container startup 
COPY --chown=steam --chmod=770 startup.sh .

CMD [ "bash","-c","./startup.sh"]



